/*
 * buildopts.h 
 * Automatically generated
 */

#define LOADABLE_MODULES 1
#define AST_MODULE_RES_ADSI 1
#define AST_MODULE_CHAN_LOCAL 1
#define AST_MODULE_APP_VOICEMAIL 1
#define AST_MODULE_RES_MONITOR 1
#define AST_MODULE_RES_AGI 1
#define AST_MODULE_RES_AEL_SHARE 1
#define AST_MODULE_G711_NEW_ALGORITHM 1
#define AST_MODULE_CHAN_USBRADIO 1
#define AST_MODULE_DEBUG_THREADS 1
#define AST_DEVMODE 1
#define AST_BUILDOPT_SUM "4fc3f7b2ee0eecde874c8c76b2b33b95"
#define AST_BUILDOPTS "LOADABLE_MODULES"
